# Generated by Django 4.2 on 2023-06-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0005_order_status_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
