# Generated by Django 4.2 on 2023-05-20 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
        migrations.AddField(
            model_name='dishcategory',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
